# runtime: php83
# env: standard
# service: default

# env_variables:
#   APP_KEY: base64:pIIV470Dxv+9V4AvGYcqXlJfXs80K7vaP4WKHKm1Uvs=
#   APP_ENV: production
#   DB_CONNECTION: mysql
#   DB_HOST: localhost
#   DB_HOST: 34.50.73.71
#   DB_PORT: 3306
#   DB_DATABASE: greenquest_db
#   DB_USERNAME: root
#   DB_PASSWORD: Bismillah.Capstone.Lancar
#   GOOGLE_CLOUD_PROJECT: greenquest-442806
#   # GOOGLE_APPLICATION_CREDENTIALS: /var/app/current/app.json
#   # FILESYSTEM_DISK: google

# handlers:
#   - url: /favicon\.ico
#     static_files: public/favicon.ico
#     upload: public/favicon.ico

#   - url: /robots\.txt
#     static_files: public/robots.txt
#     upload: public/robots.txt

#   - url: /static
#     static_dir: public/static

#   - url: /.*
#     script: auto

# # - url: /storage
# #   static_dir: storage